# Basic Stats
Quick intro to stats

## Mean / Median

In [17]:
import numpy as np
import pandas as pd
from scipy import stats

a = np.array([5,40,42,45,50,55,60,65,70,400])
print(a)



[  5  40  42  45  50  55  60  65  70 400]


In [18]:
## TODO: calculate mean & median
## Hint : np.mean  / np.median
print (np.mean(a)) # 83.2
print (np.median(a)) # 52.5 

83.2
52.5


In [19]:
## Trimmed mean of 10%
## Hint : stats.trim_mean(a,  0.1)
stats.trim_mean(a, 0.1) # 10% # 53.375

53.375

## Standard Deviation

In [20]:
import numpy as np
import pandas as pd
from scipy import stats

city1 = np.array([30,32,35,40,45,48,50])
city2 = np.array([10,15,20,40,60,65,70])

print(city1)
print(city2)


[30 32 35 40 45 48 50]
[10 15 20 40 60 65 70]


In [21]:
###Mean - both are 40
print(np.mean(city1))    # 40.0
print(np.mean(city2))   # 40.0 



40.0
40.0


In [22]:
## Variance
## Hint : np.var

print(np.var(city1))   # 54.0
print(np.var(city2))   #  550.0  <- much larger than var(city1)

54.0
550.0


In [23]:
## Standard Deviation
## Hint : np.std()

print(np.std(city1))    #  7.34846922835
print(np.std(city2))   # 23.4520787991  <-- larger than sd(city1)


7.3484692283495345
23.45207879911715


## Quartiles / Percentages

In [24]:
salaries = np.array([5,40,42,45,50,55,60,65,70,400])

In [25]:
## Calculate standard percentiles : 25% (q1), 50% (q2), 75% (q3)
## np.percentile(a, [.25,.50,.75])
print (np.percentile(salaries, [25, 50, 75])) 

[42.75 52.5  63.75]


In [26]:
## Find out 90 percentile
np.percentile(salaries, 90)

102.99999999999989

##  Correlation

In [27]:
import numpy as np
import pandas as pd

bills = np.array([50,30,60,40,65,20,10,15,25,35])
tips= np.array([12,7,13,8,15,5,2,2,3,4])

print(bills)
print(tips)

[50 30 60 40 65 20 10 15 25 35]
[12  7 13  8 15  5  2  2  3  4]


In [28]:
## Correlation
## Hint : np.corrcoef
np.corrcoef(tips,bills)

## Question : is there a strong correlation between bill amount and tip amount?

array([[1.        , 0.95221535],
       [0.95221535, 1.        ]])

### Using Pandas Describe method

In [29]:
import pandas as pd
df = pd.DataFrame({'bill': [50,30,60,40,65,20,10,15,25,35], 'tip': [12,7,13,8,15,5,2,2,3,4] })
df

bill  tip
0    50   12
1    30    7
2    60   13
3    40    8
4    65   15
5    20    5
6    10    2
7    15    2
8    25    3
9    35    4

In [30]:
df.describe()

bill        tip
count  10.000000  10.000000
mean   35.000000   7.100000
std    18.708287   4.771443
min    10.000000   2.000000
25%    21.250000   3.250000
50%    32.500000   6.000000
75%    47.500000  11.000000
max    65.000000  15.000000